name: Build Release

on: 
  workflow_dispatch:

env:
  packageName: "com.nolatools.furmaskgenerator"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: "Packages/${{env.packageName}}/package.json"
            prop_path: "version"
    
      - name: Set Environment Variables
        run: |
          echo "zipFile=${{ env.packageName }}-${{ steps.version.outputs.prop }}" >> $GITHUB_ENV
          echo "unityPackage=${{ env.packageName }}-${{ steps.version.outputs.prop }}.unitypackage" >> $GITHUB_ENV
          echo "zipPath=${{ env.packageName }}-${{ steps.version.outputs.prop }}.zip" >> $GITHUB_ENV
          echo "version=${{ steps.version.outputs.prop }}" >> $GITHUB_ENV
          
      - name: Create Zip
        run: |
          cd "Packages/${{env.packageName}}"
          zip -r "../../${{env.zipPath}}" .
        
      - name: Make Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ env.version }}"
          files: |
            ${{ env.zipPath }}
            Packages/${{ env.packageName }}/package.json